<?php
/**
 * SwagPaypalPosSalesChannelRunLogApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Admin API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Admin API.  For a better overview, all CRUD-endpoints are hidden by default. If you want to show also CRUD-endpoints add the query parameter `type=jsonapi`.
 *
 * OpenAPI spec version: 6.4.7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.31
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * SwagPaypalPosSalesChannelRunLogApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SwagPaypalPosSalesChannelRunLogApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createSwagPaypalPosSalesChannelRunLog
     *
     * Create a new Swag Paypal Pos Sales Channel Run Log resources
     *
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogBody $body body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse200473
     */
    public function createSwagPaypalPosSalesChannelRunLog($body = null, $_response = null)
    {
        list($response) = $this->createSwagPaypalPosSalesChannelRunLogWithHttpInfo($body, $_response);
        return $response;
    }

    /**
     * Operation createSwagPaypalPosSalesChannelRunLogWithHttpInfo
     *
     * Create a new Swag Paypal Pos Sales Channel Run Log resources
     *
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogBody $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\InlineResponse200473, HTTP status code, HTTP response headers (array of strings)
     */
    public function createSwagPaypalPosSalesChannelRunLogWithHttpInfo($body = null, $_response = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse200473';
        $request = $this->createSwagPaypalPosSalesChannelRunLogRequest($body, $_response);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse200473',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createSwagPaypalPosSalesChannelRunLogAsync
     *
     * Create a new Swag Paypal Pos Sales Channel Run Log resources
     *
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogBody $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSwagPaypalPosSalesChannelRunLogAsync($body = null, $_response = null)
    {
        return $this->createSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo($body, $_response)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo
     *
     * Create a new Swag Paypal Pos Sales Channel Run Log resources
     *
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogBody $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo($body = null, $_response = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse200473';
        $request = $this->createSwagPaypalPosSalesChannelRunLogRequest($body, $_response);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createSwagPaypalPosSalesChannelRunLog'
     *
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogBody $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createSwagPaypalPosSalesChannelRunLogRequest($body = null, $_response = null)
    {

        $resourcePath = '/swag-paypal-pos-sales-channel-run-log';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($_response !== null) {
            $queryParams['_response'] = ObjectSerializer::toQueryValue($_response, null);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                ['application/vnd.api+json', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createSwagPaypalPosSalesChannelRunLog
     *
     * Create a new Swag Paypal Pos Sales Channel Run Log resources
     *
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogBody $body body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse200473
     */
    public function createSwagPaypalPosSalesChannelRunLog($body = null, $_response = null)
    {
        list($response) = $this->createSwagPaypalPosSalesChannelRunLogWithHttpInfo($body, $_response);
        return $response;
    }

    /**
     * Operation createSwagPaypalPosSalesChannelRunLogWithHttpInfo
     *
     * Create a new Swag Paypal Pos Sales Channel Run Log resources
     *
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogBody $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\InlineResponse200473, HTTP status code, HTTP response headers (array of strings)
     */
    public function createSwagPaypalPosSalesChannelRunLogWithHttpInfo($body = null, $_response = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse200473';
        $request = $this->createSwagPaypalPosSalesChannelRunLogRequest($body, $_response);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse200473',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createSwagPaypalPosSalesChannelRunLogAsync
     *
     * Create a new Swag Paypal Pos Sales Channel Run Log resources
     *
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogBody $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSwagPaypalPosSalesChannelRunLogAsync($body = null, $_response = null)
    {
        return $this->createSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo($body, $_response)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo
     *
     * Create a new Swag Paypal Pos Sales Channel Run Log resources
     *
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogBody $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo($body = null, $_response = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse200473';
        $request = $this->createSwagPaypalPosSalesChannelRunLogRequest($body, $_response);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createSwagPaypalPosSalesChannelRunLog'
     *
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogBody $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createSwagPaypalPosSalesChannelRunLogRequest($body = null, $_response = null)
    {

        $resourcePath = '/swag-paypal-pos-sales-channel-run-log';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($_response !== null) {
            $queryParams['_response'] = ObjectSerializer::toQueryValue($_response, null);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                ['application/vnd.api+json', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteSwagPaypalPosSalesChannelRunLog
     *
     * Delete a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteSwagPaypalPosSalesChannelRunLog($id, $_response = null)
    {
        $this->deleteSwagPaypalPosSalesChannelRunLogWithHttpInfo($id, $_response);
    }

    /**
     * Operation deleteSwagPaypalPosSalesChannelRunLogWithHttpInfo
     *
     * Delete a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteSwagPaypalPosSalesChannelRunLogWithHttpInfo($id, $_response = null)
    {
        $returnType = '';
        $request = $this->deleteSwagPaypalPosSalesChannelRunLogRequest($id, $_response);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteSwagPaypalPosSalesChannelRunLogAsync
     *
     * Delete a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSwagPaypalPosSalesChannelRunLogAsync($id, $_response = null)
    {
        return $this->deleteSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo($id, $_response)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo
     *
     * Delete a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo($id, $_response = null)
    {
        $returnType = '';
        $request = $this->deleteSwagPaypalPosSalesChannelRunLogRequest($id, $_response);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteSwagPaypalPosSalesChannelRunLog'
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteSwagPaypalPosSalesChannelRunLogRequest($id, $_response = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteSwagPaypalPosSalesChannelRunLog'
            );
        }

        $resourcePath = '/swag-paypal-pos-sales-channel-run-log/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($_response !== null) {
            $queryParams['_response'] = ObjectSerializer::toQueryValue($_response, null);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSwagPaypalPosSalesChannelRunLog
     *
     * Detailed information about a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse200473
     */
    public function getSwagPaypalPosSalesChannelRunLog($id)
    {
        list($response) = $this->getSwagPaypalPosSalesChannelRunLogWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation getSwagPaypalPosSalesChannelRunLogWithHttpInfo
     *
     * Detailed information about a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\InlineResponse200473, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSwagPaypalPosSalesChannelRunLogWithHttpInfo($id)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse200473';
        $request = $this->getSwagPaypalPosSalesChannelRunLogRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse200473',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSwagPaypalPosSalesChannelRunLogAsync
     *
     * Detailed information about a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSwagPaypalPosSalesChannelRunLogAsync($id)
    {
        return $this->getSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo
     *
     * Detailed information about a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo($id)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse200473';
        $request = $this->getSwagPaypalPosSalesChannelRunLogRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSwagPaypalPosSalesChannelRunLog'
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSwagPaypalPosSalesChannelRunLogRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getSwagPaypalPosSalesChannelRunLog'
            );
        }

        $resourcePath = '/swag-paypal-pos-sales-channel-run-log/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSwagPaypalPosSalesChannelRunLogList
     *
     * List with basic information of Swag Paypal Pos Sales Channel Run Log resources
     *
     * @param  int $limit Max amount of resources to be returned in a page (optional)
     * @param  int $page The page to be returned (optional)
     * @param  string $query Encoded SwagQL in JSON (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse200471
     */
    public function getSwagPaypalPosSalesChannelRunLogList($limit = null, $page = null, $query = null)
    {
        list($response) = $this->getSwagPaypalPosSalesChannelRunLogListWithHttpInfo($limit, $page, $query);
        return $response;
    }

    /**
     * Operation getSwagPaypalPosSalesChannelRunLogListWithHttpInfo
     *
     * List with basic information of Swag Paypal Pos Sales Channel Run Log resources
     *
     * @param  int $limit Max amount of resources to be returned in a page (optional)
     * @param  int $page The page to be returned (optional)
     * @param  string $query Encoded SwagQL in JSON (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\InlineResponse200471, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSwagPaypalPosSalesChannelRunLogListWithHttpInfo($limit = null, $page = null, $query = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse200471';
        $request = $this->getSwagPaypalPosSalesChannelRunLogListRequest($limit, $page, $query);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse200471',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSwagPaypalPosSalesChannelRunLogListAsync
     *
     * List with basic information of Swag Paypal Pos Sales Channel Run Log resources
     *
     * @param  int $limit Max amount of resources to be returned in a page (optional)
     * @param  int $page The page to be returned (optional)
     * @param  string $query Encoded SwagQL in JSON (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSwagPaypalPosSalesChannelRunLogListAsync($limit = null, $page = null, $query = null)
    {
        return $this->getSwagPaypalPosSalesChannelRunLogListAsyncWithHttpInfo($limit, $page, $query)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSwagPaypalPosSalesChannelRunLogListAsyncWithHttpInfo
     *
     * List with basic information of Swag Paypal Pos Sales Channel Run Log resources
     *
     * @param  int $limit Max amount of resources to be returned in a page (optional)
     * @param  int $page The page to be returned (optional)
     * @param  string $query Encoded SwagQL in JSON (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSwagPaypalPosSalesChannelRunLogListAsyncWithHttpInfo($limit = null, $page = null, $query = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse200471';
        $request = $this->getSwagPaypalPosSalesChannelRunLogListRequest($limit, $page, $query);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSwagPaypalPosSalesChannelRunLogList'
     *
     * @param  int $limit Max amount of resources to be returned in a page (optional)
     * @param  int $page The page to be returned (optional)
     * @param  string $query Encoded SwagQL in JSON (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSwagPaypalPosSalesChannelRunLogListRequest($limit = null, $page = null, $query = null)
    {

        $resourcePath = '/swag-paypal-pos-sales-channel-run-log';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit, null);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page, null);
        }
        // query params
        if ($query !== null) {
            $queryParams['query'] = ObjectSerializer::toQueryValue($query, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateSwagPaypalPosSalesChannelRunLog
     *
     * Partially update information about a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogIdBody $body Partially update information about a Swag Paypal Pos Sales Channel Run Log resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse200473
     */
    public function updateSwagPaypalPosSalesChannelRunLog($id, $body = null, $_response = null)
    {
        list($response) = $this->updateSwagPaypalPosSalesChannelRunLogWithHttpInfo($id, $body, $_response);
        return $response;
    }

    /**
     * Operation updateSwagPaypalPosSalesChannelRunLogWithHttpInfo
     *
     * Partially update information about a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogIdBody $body Partially update information about a Swag Paypal Pos Sales Channel Run Log resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\InlineResponse200473, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateSwagPaypalPosSalesChannelRunLogWithHttpInfo($id, $body = null, $_response = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse200473';
        $request = $this->updateSwagPaypalPosSalesChannelRunLogRequest($id, $body, $_response);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse200473',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateSwagPaypalPosSalesChannelRunLogAsync
     *
     * Partially update information about a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogIdBody $body Partially update information about a Swag Paypal Pos Sales Channel Run Log resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSwagPaypalPosSalesChannelRunLogAsync($id, $body = null, $_response = null)
    {
        return $this->updateSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo($id, $body, $_response)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo
     *
     * Partially update information about a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogIdBody $body Partially update information about a Swag Paypal Pos Sales Channel Run Log resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo($id, $body = null, $_response = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse200473';
        $request = $this->updateSwagPaypalPosSalesChannelRunLogRequest($id, $body, $_response);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateSwagPaypalPosSalesChannelRunLog'
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogIdBody $body Partially update information about a Swag Paypal Pos Sales Channel Run Log resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateSwagPaypalPosSalesChannelRunLogRequest($id, $body = null, $_response = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling updateSwagPaypalPosSalesChannelRunLog'
            );
        }

        $resourcePath = '/swag-paypal-pos-sales-channel-run-log/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($_response !== null) {
            $queryParams['_response'] = ObjectSerializer::toQueryValue($_response, null);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                ['application/vnd.api+json', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateSwagPaypalPosSalesChannelRunLog
     *
     * Partially update information about a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogIdBody $body Partially update information about a Swag Paypal Pos Sales Channel Run Log resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse200473
     */
    public function updateSwagPaypalPosSalesChannelRunLog($id, $body = null, $_response = null)
    {
        list($response) = $this->updateSwagPaypalPosSalesChannelRunLogWithHttpInfo($id, $body, $_response);
        return $response;
    }

    /**
     * Operation updateSwagPaypalPosSalesChannelRunLogWithHttpInfo
     *
     * Partially update information about a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogIdBody $body Partially update information about a Swag Paypal Pos Sales Channel Run Log resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\InlineResponse200473, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateSwagPaypalPosSalesChannelRunLogWithHttpInfo($id, $body = null, $_response = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse200473';
        $request = $this->updateSwagPaypalPosSalesChannelRunLogRequest($id, $body, $_response);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse200473',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Failure',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateSwagPaypalPosSalesChannelRunLogAsync
     *
     * Partially update information about a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogIdBody $body Partially update information about a Swag Paypal Pos Sales Channel Run Log resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSwagPaypalPosSalesChannelRunLogAsync($id, $body = null, $_response = null)
    {
        return $this->updateSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo($id, $body, $_response)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo
     *
     * Partially update information about a Swag Paypal Pos Sales Channel Run Log resource
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogIdBody $body Partially update information about a Swag Paypal Pos Sales Channel Run Log resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSwagPaypalPosSalesChannelRunLogAsyncWithHttpInfo($id, $body = null, $_response = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse200473';
        $request = $this->updateSwagPaypalPosSalesChannelRunLogRequest($id, $body, $_response);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateSwagPaypalPosSalesChannelRunLog'
     *
     * @param  string $id Identifier for the swag_paypal_pos_sales_channel_run_log (required)
     * @param  \Swagger\Client\Model\SwagpaypalpossaleschannelrunlogIdBody $body Partially update information about a Swag Paypal Pos Sales Channel Run Log resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateSwagPaypalPosSalesChannelRunLogRequest($id, $body = null, $_response = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling updateSwagPaypalPosSalesChannelRunLog'
            );
        }

        $resourcePath = '/swag-paypal-pos-sales-channel-run-log/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($_response !== null) {
            $queryParams['_response'] = ObjectSerializer::toQueryValue($_response, null);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                ['application/vnd.api+json', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
